name: Build clover debian package

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: noetic
    - name: Install dependencies
      run: |
        sudo apt-get install python3-bloom fakeroot debhelper dpkg-dev ros-noetic-rosbash
    - name: Build package
      run: |
        source /opt/ros/noetic/setup.bash
        roscd clover_app
        bloom-generate rosdebian
        fakeroot debian/rules binary
