name: Pylint

on: [pull_request, push]

jobs:
  lint-multi-os:
  
    name: Lint ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python 3.9
      with:
        python-version: 3.9
    - uses: actions/cache@v1
      with:
        key: v0-${{ runner.os }}-pip-lint-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-lint-
          v0-${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[lint]
    - name: Run black
      run: black --check --verbose .
    - name: Run flake8
      run: flake8 --statistics  # --exclude docs
    - name: Run isort
      run: isort -cv .
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
